from mindlint.config.defaults import (
    DEFAULT_OLLAMA_MODEL,
    DEFAULT_OLLAMA_URL,
    REQUIRED_FOOTER_DISCLOSURE,
    REQUIRED_IMAGE_DISCLOSURE,
)

__all__ = [
    "DEFAULT_OLLAMA_MODEL",
    "DEFAULT_OLLAMA_URL",
    "REQUIRED_FOOTER_DISCLOSURE",
    "REQUIRED_IMAGE_DISCLOSURE",
]
