name: CI

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    name: Flutter CI
    uses: ./.github/workflows/reusable/flutter-ci.yml
    with:
      collect-coverage: true
      coverage-threshold: ${{ vars.COVERAGE_THRESHOLD || '' }}
